# Customer Churn Prediction

# 4. Feature Engineering

## Business Objective

Feature engineering is the process of transforming raw data into a format suitable for machine learning algorithms.

The objective of this phase is to:

- Prepare the dataset for model training.
- Convert categorical variables into numerical format.
- Remove irrelevant features.
- Scale numerical variables where necessary.
- Save the processed dataset for machine learning.

In [2]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

In [3]:
df = pd.read_csv("../data/processed/cleaned_telco_customer_churn.csv")

df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7032 entries, 0 to 7031
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7032 non-null   str
 1   gender            7032 non-null   str
 2   SeniorCitizen     7032 non-null   int64
 3   Partner           7032 non-null   str
 4   Dependents        7032 non-null   str
 5   tenure            7032 non-null   int64
 6   PhoneService      7032 non-null   str
 7   MultipleLines     7032 non-null   str
 8   InternetService   7032 non-null   str
 9   OnlineSecurity    7032 non-null   str
 10  OnlineBackup      7032 non-null   str
 11  DeviceProtection  7032 non-null   str
 12  TechSupport       7032 non-null   str
 13  StreamingTV       7032 non-null   str
 14  StreamingMovies   7032 non-null   str
 15  Contract          7032 non-null   str
 16  PaperlessBilling  7032 non-null   str
 17  PaymentMethod     7032 non-null   str
 18  MonthlyCharges    7032 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7032 non-null   str
dtypes: float64(2), int64(2), str(17)
memory usage: 1.8 MB

## 4.1 Remove Identifier Column

### Why remove `customerID`?

The `customerID` column is a unique identifier and does not contain predictive information about customer churn.

Removing identifier columns helps the model focus on meaningful customer attributes.

In [5]:
# Remove customerID column

df = df.drop(columns=["customerID"])

df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [6]:
df.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='str')

## 4.2 Separate Features and Target

Machine learning models learn patterns from input features (`X`) to predict the target variable (`y`).

- **Features (`X`)** represent customer attributes.
- **Target (`y`)** represents whether the customer churned.

In [7]:
# Separate features and target

X = df.drop(columns=["Churn"])

y = df["Churn"]

In [8]:
print("Features Shape :", X.shape)
print("Target Shape :", y.shape)

Features Shape : (7032, 19)
Target Shape : (7032,)

## 4.3 Encode the Target Variable

### Why encode the target variable?

The target variable (`Churn`) contains categorical values (`Yes` and `No`).

Machine learning algorithms require numerical input. Therefore, the target variable is converted into binary values:

- **No → 0**
- **Yes → 1**

This binary representation is suitable for classification models.

In [9]:
# Encode target variable

y = y.map({
    "No": 0,
    "Yes": 1
})

y.head()

0    0
1    0
2    1
3    0
4    1
Name: Churn, dtype: int64

In [10]:
y.value_counts()

Churn
0    5163
1    1869
Name: count, dtype: int64

## 4.4 Encode Categorical Features

### Why encode categorical features?

Machine learning algorithms require numerical input.

Most categorical features in this dataset are nominal, meaning they do not have a meaningful numerical order.

Therefore, One-Hot Encoding is used to convert categorical variables into binary indicator columns while avoiding artificial numerical relationships.

In [11]:
# Identify categorical columns

categorical_columns = X.select_dtypes(include=["object"]).columns

categorical_columns

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_8308\1007144857.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = X.select_dtypes(include=["object"]).columns

Index(['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod'],
      dtype='str')

In [12]:
# Apply One-Hot Encoding

X = pd.get_dummies(
    X,
    columns=categorical_columns,
    drop_first=True,
    dtype=int
)

X.head()

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,29.85,29.85,0,1,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
1,0,34,56.95,1889.50,1,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,1
2,0,2,53.85,108.15,1,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,1
3,0,45,42.30,1840.75,1,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
4,0,2,70.70,151.65,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,1,0

In [13]:
print("Shape after encoding:", X.shape)

Shape after encoding: (7032, 30)

## 4.5 Feature Scaling

### Why perform feature scaling?

Feature scaling transforms numerical features so that they are on a similar scale.

Algorithms such as Logistic Regression, K-Nearest Neighbors, Support Vector Machines, and Neural Networks are sensitive to feature magnitudes and generally perform better when features are scaled.

Tree-based models such as Decision Trees, Random Forests, and XGBoost do not require feature scaling.

In [14]:
# Numerical columns

numerical_columns = [
    "SeniorCitizen",
    "tenure",
    "MonthlyCharges",
    "TotalCharges"
]

numerical_columns

['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges']

In [15]:
# Create a copy before scaling

X_scaled = X.copy()

In [16]:
scaler = StandardScaler()

X_scaled[numerical_columns] = scaler.fit_transform(
    X_scaled[numerical_columns]
)

X_scaled.head()

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,-0.440327,-1.280248,-1.161694,-0.994194,0,1,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
1,-0.440327,0.064303,-0.260878,-0.173740,1,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,1
2,-0.440327,-1.239504,-0.363923,-0.959649,1,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,1
3,-0.440327,0.512486,-0.747850,-0.195248,1,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
4,-0.440327,-1.239504,0.196178,-0.940457,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,1,0

In [17]:
comparison = pd.DataFrame({
    "Original": X[numerical_columns].iloc[0],
    "Scaled": X_scaled[numerical_columns].iloc[0]
})

comparison

                Original    Scaled
SeniorCitizen       0.00 -0.440327
tenure              1.00 -1.280248
MonthlyCharges     29.85 -1.161694
TotalCharges       29.85 -0.994194

In [18]:
# Save processed datasets

X.to_csv("../data/processed/X_unscaled.csv", index=False)
X_scaled.to_csv("../data/processed/X_scaled.csv", index=False)
y.to_csv("../data/processed/y.csv", index=False)

# 4.6 Save Preprocessing Objects

## Why Save the Preprocessing Objects?

To ensure consistent predictions during deployment, the preprocessing objects used during model training must be preserved.

The following objects are saved:

- **StandardScaler** – Stores the scaling parameters (mean and standard deviation) learned from the training data. This ensures that new customer data is transformed using the exact same scaling process before making predictions.

- **Feature Column Names** – Stores the order and names of the features used during model training. This guarantees that future input data matches the structure expected by the trained machine learning model.

Saving these preprocessing objects enables the model to be deployed in applications such as Streamlit without introducing inconsistencies between training and prediction.

In [19]:
import joblib

# Save the fitted scaler
joblib.dump(
    scaler,
    "../models/scaler.pkl"
)

print("Scaler saved successfully!")

Scaler saved successfully!

In [20]:
# Save feature column names

joblib.dump(
    X_scaled.columns.tolist(),
    "../models/feature_columns.pkl"
)

print("Feature columns saved successfully!")

Feature columns saved successfully!